-- Preset exercise library (shared — user_id = NULL).
-- Run once after schema.sql. Safe to re-run (ON CONFLICT DO NOTHING).

insert into exercises (id, user_id, name, muscle, description, is_custom) values
-- CHEST
('e1',  null, 'Bench Press',            'chest',     'Flat barbell press, king of chest exercises',                   false),
('e2',  null, 'Incline Bench Press',    'chest',     'Barbell press at 30-45° incline, upper chest focus',            false),
('e3',  null, 'Decline Bench Press',    'chest',     'Barbell press on decline, lower chest focus',                   false),
('e4',  null, 'Dumbbell Flyes',         'chest',     'Chest stretch and squeeze with dumbbells',                      false),
('e5',  null, 'Incline Dumbbell Press', 'chest',     'Dumbbell press on incline bench',                               false),
('e6',  null, 'Cable Crossover',        'chest',     'Cable fly for constant tension on chest',                       false),
('e7',  null, 'Chest Dip',              'chest',     'Bodyweight dip leaning forward for chest',                      false),
('e8',  null, 'Push-Up',                'chest',     'Classic bodyweight chest exercise',                             false),
('e9',  null, 'Pec Deck',               'chest',     'Machine fly for chest isolation',                               false),
('e10', null, 'Dumbbell Pullover',      'chest',     'Targets chest and lat with arc motion',                         false),
-- BACK
('e11', null, 'Deadlift',               'back',      'Full-body pull from floor, king of back builders',              false),
('e12', null, 'Pull-Up',                'back',      'Overhand grip bodyweight pull',                                 false),
('e13', null, 'Chin-Up',                'back',      'Underhand grip bodyweight pull, more bicep',                    false),
('e14', null, 'Barbell Row',            'back',      'Bent-over barbell row for mid and upper back',                  false),
('e15', null, 'Dumbbell Row',           'back',      'Single-arm row for back thickness',                             false),
('e16', null, 'T-Bar Row',              'back',      'Chest-supported or free T-bar for mass',                        false),
('e17', null, 'Lat Pulldown',           'back',      'Cable pulldown for lat width',                                  false),
('e18', null, 'Seated Cable Row',       'back',      'Cable row for mid-back thickness',                              false),
('e19', null, 'Rack Pull',              'back',      'Partial deadlift from knee height for upper back',              false),
('e20', null, 'Good Morning',           'back',      'Barbell hip hinge for lower back and hamstrings',               false),
('e21', null, 'Hyperextension',         'back',      'Back extension on GHD or roman chair',                         false),
('e22', null, 'Straight-Arm Pulldown',  'back',      'Cable move for lat isolation',                                  false),
-- SHOULDERS
('e23', null, 'Overhead Press',         'shoulders', 'Barbell press overhead for overall shoulder mass',              false),
('e24', null, 'Dumbbell Shoulder Press','shoulders', 'Seated or standing dumbbell press overhead',                    false),
('e25', null, 'Arnold Press',           'shoulders', 'Rotational DB press hitting all 3 delt heads',                  false),
('e26', null, 'Lateral Raise',          'shoulders', 'Side raise for medial delt width',                             false),
('e27', null, 'Front Raise',            'shoulders', 'Forward raise for anterior delt',                              false),
('e28', null, 'Rear Delt Fly',          'shoulders', 'Bent-over fly for rear delts and upper back',                   false),
('e29', null, 'Face Pull',              'shoulders', 'Cable pull to face for rear delt and rotator cuff',             false),
('e30', null, 'Upright Row',            'shoulders', 'Barbell or cable row to chin for traps and delts',              false),
('e31', null, 'Shrugs',                 'shoulders', 'Barbell or dumbbell shrug for traps',                          false),
('e32', null, 'Cable Lateral Raise',    'shoulders', 'Constant-tension lateral raise on cable',                      false),
-- BICEPS
('e33', null, 'Barbell Curl',           'biceps',    'Classic barbell curl for bicep mass',                           false),
('e34', null, 'Dumbbell Curl',          'biceps',    'Alternating or simultaneous dumbbell curl',                     false),
('e35', null, 'Hammer Curl',            'biceps',    'Neutral grip for brachialis and brachioradialis',               false),
('e36', null, 'Incline Dumbbell Curl',  'biceps',    'Long-head bicep stretch on incline bench',                      false),
('e37', null, 'Cable Curl',             'biceps',    'Constant tension curl on cable machine',                        false),
('e38', null, 'Preacher Curl',          'biceps',    'EZ-bar or dumbbell curl on preacher pad',                       false),
('e39', null, 'Concentration Curl',     'biceps',    'Seated single-arm curl for peak contraction',                   false),
('e40', null, 'Spider Curl',            'biceps',    'Prone incline curl for full range of motion',                   false),
('e41', null, 'EZ-Bar Curl',            'biceps',    'Reduces wrist strain vs straight bar',                          false),
-- TRICEPS
('e42', null, 'Tricep Pushdown',        'triceps',   'Cable pushdown for tricep isolation',                           false),
('e43', null, 'Overhead Tricep Extension','triceps', 'Long-head tricep stretch overhead',                             false),
('e44', null, 'Skull Crusher',          'triceps',   'EZ-bar or dumbbell lying tricep extension',                     false),
('e45', null, 'Tricep Dip',             'triceps',   'Upright torso bodyweight dip for triceps',                      false),
('e46', null, 'Close-Grip Bench Press', 'triceps',   'Narrow grip bench for tricep mass',                             false),
('e47', null, 'Cable Kickback',         'triceps',   'Rear cable extension for tricep squeeze',                       false),
('e48', null, 'Diamond Push-Up',        'triceps',   'Narrow hand push-up for triceps',                               false),
-- LEGS
('e49', null, 'Squat',                  'legs',      'King of leg exercises, full quad and glute builder',            false),
('e50', null, 'Front Squat',            'legs',      'Barbell in front, more quad emphasis',                          false),
('e51', null, 'Romanian Deadlift',      'legs',      'Hip hinge targeting hamstrings and glutes',                     false),
('e52', null, 'Leg Press',              'legs',      'Machine press for quads, hamstrings and glutes',                false),
('e53', null, 'Leg Curl',               'legs',      'Lying or seated hamstring isolation',                           false),
('e54', null, 'Leg Extension',          'legs',      'Machine quad isolation',                                        false),
('e55', null, 'Hip Thrust',             'legs',      'Barbell glute bridge for maximum glute activation',             false),
('e56', null, 'Calf Raise',             'legs',      'Standing calf raise for gastrocnemius',                         false),
('e57', null, 'Seated Calf Raise',      'legs',      'Seated version targeting soleus',                               false),
('e58', null, 'Bulgarian Split Squat',  'legs',      'Rear-foot elevated split squat',                                false),
('e59', null, 'Hack Squat',             'legs',      'Machine or barbell hack squat for quads',                       false),
('e60', null, 'Sumo Deadlift',          'legs',      'Wide stance pull targeting inner thigh and glutes',             false),
('e61', null, 'Goblet Squat',           'legs',      'Front-loaded squat with dumbbell or kettlebell',                false),
('e62', null, 'Lunges',                 'legs',      'Walking or stationary lunges for legs',                         false),
('e63', null, 'Step-Up',                'legs',      'Box step-up for quad and glute activation',                     false),
('e64', null, 'Glute Bridge',           'legs',      'Floor hip extension targeting glutes',                          false),
-- CORE
('e65', null, 'Plank',                  'core',      'Isometric core hold for stability',                             false),
('e66', null, 'Crunch',                 'core',      'Classic upper ab crunch',                                       false),
('e67', null, 'Sit-Up',                 'core',      'Full range of motion abdominal exercise',                       false),
('e68', null, 'Leg Raise',              'core',      'Lying or hanging lower ab exercise',                            false),
('e69', null, 'Russian Twist',          'core',      'Rotational core exercise for obliques',                         false),
('e70', null, 'Ab Rollout',             'core',      'Wheel rollout for deep core and stability',                     false),
('e71', null, 'Cable Crunch',           'core',      'Weighted cable crunch for ab development',                      false),
('e72', null, 'Hanging Leg Raise',      'core',      'Bar hang with leg raise for lower abs',                         false),
('e73', null, 'Side Plank',             'core',      'Lateral isometric hold for obliques',                           false),
('e74', null, 'Mountain Climber',       'core',      'Dynamic plank with alternating knee drives',                    false),
('e75', null, 'Dead Bug',               'core',      'Lying opposite arm-leg extension for stability',                false),
-- CARDIO
('e76', null, 'Treadmill Run',          'cardio',    'Steady-state or interval running',                              false),
('e77', null, 'Rowing Machine',         'cardio',    'Full-body cardio on erg rower',                                 false),
('e78', null, 'Stationary Bike',        'cardio',    'Low-impact cycling cardio',                                     false),
('e79', null, 'Jump Rope',              'cardio',    'High-calorie cardio and coordination',                          false),
('e80', null, 'Battle Ropes',           'cardio',    'High-intensity rope slams and waves',                           false),
('e81', null, 'Box Jump',               'cardio',    'Explosive plyometric for power and cardio',                     false),
('e82', null, 'Burpee',                 'cardio',    'Full-body conditioning movement',                               false),
('e83', null, 'Stair Climber',          'cardio',    'Machine stair climbing for legs and cardio',                    false),
-- CHEST (extra)
('e84', null, 'Machine Chest Press',    'chest',     'Selectorized machine press for chest isolation',                false),
('e85', null, 'Svend Press',            'chest',     'Squeeze two plates together and press for chest activation',    false),
('e86', null, 'Landmine Press',         'chest',     'Single-arm arc press targeting upper chest and anterior delt',  false),
-- BACK (extra)
('e87', null, 'Pendlay Row',            'back',      'Explosive barbell row reset to floor each rep for upper back',  false),
('e88', null, 'Meadows Row',            'back',      'Landmine-style single-arm row for lat thickness',               false),
('e89', null, 'Chest-Supported Row',    'back',      'Incline bench dumbbell row removing lower back from the lift',  false),
('e90', null, 'Trap Bar Deadlift',      'back',      'Hex bar deadlift — more quad-friendly than conventional',       false),
('e91', null, 'Single-Arm Lat Pulldown','back',      'Unilateral cable pulldown for lat isolation and symmetry',      false),
-- SHOULDERS (extra)
('e92', null, 'Machine Shoulder Press', 'shoulders', 'Guided press machine for shoulder safety and isolation',        false),
('e93', null, 'Cable Front Raise',      'shoulders', 'Constant-tension front raise on low cable',                    false),
('e94', null, 'Reverse Pec Deck',       'shoulders', 'Machine rear delt fly for posterior shoulder',                  false),
('e95', null, 'Landmine Lateral Raise', 'shoulders', 'Arc lateral raise with landmine for joint-friendly loading',    false),
-- BICEPS (extra)
('e96', null, 'Zottman Curl',           'biceps',    'Supinated curl up, pronated descent for full arm development',  false),
('e97', null, 'Cross Body Curl',        'biceps',    'Diagonal hammer curl targeting brachialis',                     false),
('e98', null, 'Reverse Curl',           'biceps',    'Pronated grip curl for brachioradialis and forearm thickness',  false),
-- TRICEPS (extra)
('e99',  null, 'Tate Press',            'triceps',   'Lying dumbbell extension with flared elbows for tricep mass',   false),
('e100', null, 'JM Press',              'triceps',   'Hybrid bench press and skull crusher for tricep thickness',     false),
('e101', null, 'Tricep Machine Press',  'triceps',   'Machine-assisted extension for tricep isolation',               false),
-- LEGS (extra)
('e102', null, 'Nordic Curl',           'legs',      'Bodyweight hamstring curl anchored at ankles',                  false),
('e103', null, 'Box Squat',             'legs',      'Squat to a box for controlled depth and posterior chain',       false),
('e104', null, 'Single-Leg RDL',        'legs',      'Unilateral Romanian deadlift for hamstring and balance',        false),
('e105', null, 'Reverse Lunge',         'legs',      'Backward step lunge emphasising quads and glutes',              false),
('e106', null, 'Lateral Lunge',         'legs',      'Side lunge for inner thigh and glute activation',              false),
('e107', null, 'Sissy Squat',           'legs',      'Bodyweight quad isolation with forward torso lean',             false),
('e108', null, 'Leg Abduction',         'legs',      'Machine outer hip and glute medius isolation',                  false),
('e109', null, 'Leg Adduction',         'legs',      'Machine inner thigh isolation',                                 false),
('e110', null, 'Donkey Calf Raise',     'legs',      'Bent-over calf raise for greater gastrocnemius stretch',        false),
('e111', null, 'Pistol Squat',          'legs',      'Single-leg squat for strength, mobility, and balance',          false),
('e112', null, 'Lying Leg Curl',        'legs',      'Prone hamstring curl machine for isolation',                    false),
('e113', null, 'Walking Lunge',         'legs',      'Continuous forward lunges for legs and glutes',                 false),
-- CORE (extra)
('e114', null, 'Dragon Flag',           'core',      'Advanced full-body core hold on a bench',                       false),
('e115', null, 'Pallof Press',          'core',      'Anti-rotation cable press for core stability',                  false),
('e116', null, 'Hollow Body Hold',      'core',      'Gymnastics core compression isometric hold',                    false),
('e117', null, 'V-Up',                  'core',      'Full crunch reaching hands to feet simultaneously',             false),
('e118', null, 'Bicycle Crunch',        'core',      'Alternating elbow-to-knee crunch for obliques',                 false),
('e119', null, 'Flutter Kicks',         'core',      'Lying alternating leg raise for lower abs endurance',           false),
('e120', null, 'L-Sit',                 'core',      'Isometric hold with legs parallel to ground for core strength', false),
('e121', null, 'Windshield Wipers',     'core',      'Hanging or lying rotational leg swing for obliques',            false),
-- CARDIO / CONDITIONING (extra)
('e122', null, 'Assault Bike',          'cardio',    'Air resistance bike for brutal full-body conditioning',         false),
('e123', null, 'Sled Push',             'cardio',    'Loaded sled drive for power and conditioning',                  false),
('e124', null, 'Farmer''s Walk',        'cardio',    'Loaded carry for grip, traps, core, and conditioning',          false),
('e125', null, 'Kettlebell Swing',      'cardio',    'Hip-hinge ballistic swing for power and cardio',                false),
('e126', null, 'Thruster',              'cardio',    'Front squat into overhead press for full-body conditioning',    false),
('e127', null, 'Power Clean',           'cardio',    'Olympic pull from floor to front rack for power development',   false),
('e128', null, 'Bear Crawl',            'cardio',    'Quadruped crawl for full-body stability and conditioning',      false),
('e129', null, 'Ski Erg',               'cardio',    'Upper-body pull machine mimicking cross-country skiing',        false),
('e130', null, 'Tire Flip',             'cardio',    'Explosive full-body movement flipping a heavy tire',            false)
on conflict (id) do nothing;
