// Client-side exercise catalog. Merged with the user's server library (custom
// exercises) inside the plan builder, so the picker is always well stocked.
export type CatalogExercise = { name: string; muscle: string; he: string };

export const MUSCLE_LABELS: Record<string, string> = {
  chest: "חזה",
  back: "גב",
  traps: "טרפזים",
  shoulders: "כתפיים",
  biceps: "יד קדמית",
  triceps: "יד אחורית",
  forearms: "אמות",
  quads: "ארבע ראשי",
  hamstrings: "מיתר הברך",
  glutes: "ישבן",
  calves: "תאומים",
  legs: "רגליים",
  core: "בטן וליבה",
  cardio: "אירובי",
  fullbody: "כל הגוף",
  custom: "מותאם אישית",
};

export const MUSCLE_ORDER = [
  "chest", "back", "traps", "shoulders", "biceps", "triceps", "forearms",
  "quads", "hamstrings", "glutes", "calves", "legs", "core", "cardio", "fullbody",
];

export const EXERCISE_CATALOG: CatalogExercise[] = [
  // ---------- CHEST ----------
  { name: "Bench Press", muscle: "chest", he: "לחיצת חזה במוט" },
  { name: "Incline Bench Press", muscle: "chest", he: "לחיצת חזה בשיפוע" },
  { name: "Decline Bench Press", muscle: "chest", he: "לחיצת חזה בשיפוע שלילי" },
  { name: "Dumbbell Bench Press", muscle: "chest", he: "לחיצת חזה משקולות" },
  { name: "Incline Dumbbell Press", muscle: "chest", he: "לחיצת משקולות בשיפוע" },
  { name: "Decline Dumbbell Press", muscle: "chest", he: "לחיצת משקולות בשיפוע שלילי" },
  { name: "Machine Chest Press", muscle: "chest", he: "לחיצת חזה במכונה" },
  { name: "Smith Machine Bench Press", muscle: "chest", he: "לחיצת חזה בסמית'" },
  { name: "Hammer Strength Press", muscle: "chest", he: "לחיצת חזה האמר" },
  { name: "Floor Press", muscle: "chest", he: "לחיצת חזה מהרצפה" },
  { name: "Dumbbell Flyes", muscle: "chest", he: "פרפר משקולות" },
  { name: "Incline Dumbbell Flyes", muscle: "chest", he: "פרפר משקולות בשיפוע" },
  { name: "Cable Crossover", muscle: "chest", he: "קרוסאובר בפולי" },
  { name: "Low Cable Fly", muscle: "chest", he: "פרפר פולי מלמטה" },
  { name: "High Cable Fly", muscle: "chest", he: "פרפר פולי מלמעלה" },
  { name: "Pec Deck", muscle: "chest", he: "פרפר במכונה" },
  { name: "Chest Dip", muscle: "chest", he: "מקבילים לחזה" },
  { name: "Push-Up", muscle: "chest", he: "שכיבות סמיכה" },
  { name: "Incline Push-Up", muscle: "chest", he: "שכיבות סמיכה בשיפוע" },
  { name: "Decline Push-Up", muscle: "chest", he: "שכיבות סמיכה רגליים מוגבהות" },
  { name: "Wide Push-Up", muscle: "chest", he: "שכיבות סמיכה רחבות" },
  { name: "Dumbbell Pullover", muscle: "chest", he: "פולאובר משקולת" },
  { name: "Svend Press", muscle: "chest", he: "לחיצת פלטות" },
  { name: "Landmine Press", muscle: "chest", he: "לחיצת לנדמיין" },

  // ---------- BACK ----------
  { name: "Deadlift", muscle: "back", he: "דדליפט" },
  { name: "Sumo Deadlift", muscle: "back", he: "דדליפט סומו" },
  { name: "Trap Bar Deadlift", muscle: "back", he: "דדליפט טרפ-בר" },
  { name: "Rack Pull", muscle: "back", he: "רק פול — דדליפט חלקי" },
  { name: "Pull-Up", muscle: "back", he: "מתח" },
  { name: "Wide Grip Pull-Up", muscle: "back", he: "מתח באחיזה רחבה" },
  { name: "Chin-Up", muscle: "back", he: "מתח באחיזה תחתונה" },
  { name: "Neutral Grip Pull-Up", muscle: "back", he: "מתח באחיזה ניטרלית" },
  { name: "Assisted Pull-Up", muscle: "back", he: "מתח בעזרת מכונה" },
  { name: "Lat Pulldown", muscle: "back", he: "פולי עליון" },
  { name: "Wide Grip Lat Pulldown", muscle: "back", he: "פולי עליון אחיזה רחבה" },
  { name: "Close Grip Lat Pulldown", muscle: "back", he: "פולי עליון אחיזה צרה" },
  { name: "Single-Arm Lat Pulldown", muscle: "back", he: "פולי עליון יד אחת" },
  { name: "Straight-Arm Pulldown", muscle: "back", he: "פולאובר בפולי" },
  { name: "Barbell Row", muscle: "back", he: "חתירה עם מוט" },
  { name: "Pendlay Row", muscle: "back", he: "חתירת פנדליי" },
  { name: "Dumbbell Row", muscle: "back", he: "חתירה עם משקולת" },
  { name: "Chest-Supported Row", muscle: "back", he: "חתירה בתמיכת חזה" },
  { name: "T-Bar Row", muscle: "back", he: "חתירת טי-בר" },
  { name: "Seated Cable Row", muscle: "back", he: "חתירה בישיבה בפולי" },
  { name: "Single-Arm Cable Row", muscle: "back", he: "חתירה בפולי יד אחת" },
  { name: "Meadows Row", muscle: "back", he: "חתירת מדואוס" },
  { name: "Inverted Row", muscle: "back", he: "חתירה הפוכה במתלה" },
  { name: "Machine Row", muscle: "back", he: "חתירה במכונה" },
  { name: "Seal Row", muscle: "back", he: "חתירת סיל בשכיבה" },
  { name: "Hyperextension", muscle: "back", he: "הרמת גב תחתון" },
  { name: "Reverse Hyperextension", muscle: "back", he: "הרמת גב הפוכה" },
  { name: "Superman", muscle: "back", he: "סופרמן" },

  // ---------- TRAPS ----------
  { name: "Barbell Shrug", muscle: "traps", he: "משיכת כתפיים במוט" },
  { name: "Dumbbell Shrug", muscle: "traps", he: "משיכת כתפיים משקולות" },
  { name: "Cable Shrug", muscle: "traps", he: "משיכת כתפיים בפולי" },
  { name: "Upright Row", muscle: "traps", he: "חתירה אנכית" },
  { name: "Power Shrug", muscle: "traps", he: "משיכת כתפיים נפיצה" },

  // ---------- SHOULDERS ----------
  { name: "Overhead Press", muscle: "shoulders", he: "לחיצת כתפיים במוט" },
  { name: "Seated Barbell Press", muscle: "shoulders", he: "לחיצת כתפיים בישיבה" },
  { name: "Push Press", muscle: "shoulders", he: "פוש פרס" },
  { name: "Dumbbell Shoulder Press", muscle: "shoulders", he: "לחיצת כתפיים משקולות" },
  { name: "Arnold Press", muscle: "shoulders", he: "ארנולד פרס" },
  { name: "Machine Shoulder Press", muscle: "shoulders", he: "לחיצת כתפיים במכונה" },
  { name: "Landmine Shoulder Press", muscle: "shoulders", he: "לחיצת לנדמיין לכתף" },
  { name: "Lateral Raise", muscle: "shoulders", he: "הרחקה לצדדים" },
  { name: "Cable Lateral Raise", muscle: "shoulders", he: "הרחקה לצדדים בפולי" },
  { name: "Machine Lateral Raise", muscle: "shoulders", he: "הרחקה לצדדים במכונה" },
  { name: "Leaning Lateral Raise", muscle: "shoulders", he: "הרחקה לצדדים בהטיה" },
  { name: "Front Raise", muscle: "shoulders", he: "הרמה קדמית" },
  { name: "Cable Front Raise", muscle: "shoulders", he: "הרמה קדמית בפולי" },
  { name: "Plate Front Raise", muscle: "shoulders", he: "הרמה קדמית עם פלטה" },
  { name: "Rear Delt Fly", muscle: "shoulders", he: "פרפר הפוך" },
  { name: "Reverse Pec Deck", muscle: "shoulders", he: "פרפר הפוך במכונה" },
  { name: "Cable Rear Delt Fly", muscle: "shoulders", he: "פרפר הפוך בפולי" },
  { name: "Face Pull", muscle: "shoulders", he: "פייס פול" },
  { name: "Bradford Press", muscle: "shoulders", he: "ברדפורד פרס" },
  { name: "Handstand Push-Up", muscle: "shoulders", he: "שכיבות סמיכה בעמידת ידיים" },
  { name: "Y-Raise", muscle: "shoulders", he: "הרמת Y" },
  { name: "Cuban Press", muscle: "shoulders", he: "קובן פרס" },

  // ---------- BICEPS ----------
  { name: "Barbell Curl", muscle: "biceps", he: "כפיפת מרפקים במוט" },
  { name: "EZ-Bar Curl", muscle: "biceps", he: "כפיפת מרפקים במוט EZ" },
  { name: "Dumbbell Curl", muscle: "biceps", he: "כפיפת מרפקים משקולות" },
  { name: "Alternating Dumbbell Curl", muscle: "biceps", he: "כפיפת מרפקים לסירוגין" },
  { name: "Hammer Curl", muscle: "biceps", he: "כפיפת פטיש" },
  { name: "Cross Body Curl", muscle: "biceps", he: "כפיפת פטיש חוצה גוף" },
  { name: "Incline Dumbbell Curl", muscle: "biceps", he: "כפיפת מרפקים בשיפוע" },
  { name: "Preacher Curl", muscle: "biceps", he: "כפיפת מרפקים בסקוט" },
  { name: "Machine Preacher Curl", muscle: "biceps", he: "כפיפת מרפקים במכונה" },
  { name: "Concentration Curl", muscle: "biceps", he: "כפיפת ריכוז" },
  { name: "Cable Curl", muscle: "biceps", he: "כפיפת מרפקים בפולי" },
  { name: "Bayesian Cable Curl", muscle: "biceps", he: "כפיפת מרפקים בפולי מאחור" },
  { name: "Spider Curl", muscle: "biceps", he: "ספיידר קרל" },
  { name: "Zottman Curl", muscle: "biceps", he: "זוטמן קרל" },
  { name: "Reverse Curl", muscle: "biceps", he: "כפיפת מרפקים הפוכה" },
  { name: "21s Curl", muscle: "biceps", he: "כפיפות 21" },

  // ---------- TRICEPS ----------
  { name: "Tricep Pushdown", muscle: "triceps", he: "פשיטת מרפקים בפולי" },
  { name: "Rope Pushdown", muscle: "triceps", he: "פשיטת מרפקים עם חבל" },
  { name: "Single-Arm Pushdown", muscle: "triceps", he: "פשיטת מרפקים יד אחת" },
  { name: "Overhead Tricep Extension", muscle: "triceps", he: "פשיטת מרפקים מעל הראש" },
  { name: "Rope Overhead Extension", muscle: "triceps", he: "פשיטה מעל הראש עם חבל" },
  { name: "Skull Crusher", muscle: "triceps", he: "סקאל קראשר" },
  { name: "JM Press", muscle: "triceps", he: "ג'יי-אם פרס" },
  { name: "Tate Press", muscle: "triceps", he: "טייט פרס" },
  { name: "Close-Grip Bench Press", muscle: "triceps", he: "לחיצת חזה אחיזה צרה" },
  { name: "Tricep Dip", muscle: "triceps", he: "מקבילים ליד אחורית" },
  { name: "Bench Dip", muscle: "triceps", he: "מקבילים על ספסל" },
  { name: "Diamond Push-Up", muscle: "triceps", he: "שכיבות סמיכה יהלום" },
  { name: "Cable Kickback", muscle: "triceps", he: "בעיטה אחורית בפולי" },
  { name: "Dumbbell Kickback", muscle: "triceps", he: "בעיטה אחורית עם משקולת" },
  { name: "Machine Tricep Extension", muscle: "triceps", he: "פשיטת מרפקים במכונה" },

  // ---------- FOREARMS ----------
  { name: "Wrist Curl", muscle: "forearms", he: "כפיפת שורש כף יד" },
  { name: "Reverse Wrist Curl", muscle: "forearms", he: "פשיטת שורש כף יד" },
  { name: "Behind-Back Wrist Curl", muscle: "forearms", he: "כפיפת שורש מאחורי הגב" },
  { name: "Wrist Roller", muscle: "forearms", he: "גלגלת אמות" },
  { name: "Plate Pinch", muscle: "forearms", he: "אחיזת פלטות" },
  { name: "Dead Hang", muscle: "forearms", he: "תלייה על מתח" },

  // ---------- QUADS ----------
  { name: "Squat", muscle: "quads", he: "סקוואט" },
  { name: "Front Squat", muscle: "quads", he: "סקוואט קדמי" },
  { name: "High Bar Squat", muscle: "quads", he: "סקוואט מוט גבוה" },
  { name: "Low Bar Squat", muscle: "quads", he: "סקוואט מוט נמוך" },
  { name: "Box Squat", muscle: "quads", he: "סקוואט לקופסה" },
  { name: "Goblet Squat", muscle: "quads", he: "סקוואט גובלט" },
  { name: "Hack Squat", muscle: "quads", he: "האק סקוואט" },
  { name: "Smith Machine Squat", muscle: "quads", he: "סקוואט בסמית'" },
  { name: "Belt Squat", muscle: "quads", he: "סקוואט חגורה" },
  { name: "Zercher Squat", muscle: "quads", he: "סקוואט זרשר" },
  { name: "Leg Press", muscle: "quads", he: "לחיצת רגליים" },
  { name: "Single-Leg Press", muscle: "quads", he: "לחיצת רגליים רגל אחת" },
  { name: "Leg Extension", muscle: "quads", he: "פשיטת ברכיים" },
  { name: "Bulgarian Split Squat", muscle: "quads", he: "סקוואט בולגרי" },
  { name: "Split Squat", muscle: "quads", he: "ספליט סקוואט" },
  { name: "Walking Lunge", muscle: "quads", he: "לאנג׳ בהליכה" },
  { name: "Reverse Lunge", muscle: "quads", he: "לאנג׳ אחורי" },
  { name: "Lateral Lunge", muscle: "quads", he: "לאנג׳ צידי" },
  { name: "Step-Up", muscle: "quads", he: "עליית מדרגה" },
  { name: "Sissy Squat", muscle: "quads", he: "סיסי סקוואט" },
  { name: "Pistol Squat", muscle: "quads", he: "סקוואט על רגל אחת" },
  { name: "Wall Sit", muscle: "quads", he: "ישיבת קיר" },

  // ---------- HAMSTRINGS ----------
  { name: "Romanian Deadlift", muscle: "hamstrings", he: "דדליפט רומני" },
  { name: "Stiff-Leg Deadlift", muscle: "hamstrings", he: "דדליפט רגליים ישרות" },
  { name: "Single-Leg RDL", muscle: "hamstrings", he: "דדליפט רומני על רגל אחת" },
  { name: "Lying Leg Curl", muscle: "hamstrings", he: "כפיפת ברכיים בשכיבה" },
  { name: "Seated Leg Curl", muscle: "hamstrings", he: "כפיפת ברכיים בישיבה" },
  { name: "Standing Leg Curl", muscle: "hamstrings", he: "כפיפת ברכיים בעמידה" },
  { name: "Nordic Curl", muscle: "hamstrings", he: "נורדיק קרל" },
  { name: "Glute-Ham Raise", muscle: "hamstrings", he: "הרמת ירך-ישבן" },
  { name: "Good Morning", muscle: "hamstrings", he: "גוד מורנינג" },

  // ---------- GLUTES ----------
  { name: "Hip Thrust", muscle: "glutes", he: "היפ תראסט" },
  { name: "Single-Leg Hip Thrust", muscle: "glutes", he: "היפ תראסט רגל אחת" },
  { name: "Glute Bridge", muscle: "glutes", he: "גשר ישבן" },
  { name: "Cable Pull-Through", muscle: "glutes", he: "משיכת פולי בין הרגליים" },
  { name: "Glute Kickback", muscle: "glutes", he: "בעיטת ישבן בפולי" },
  { name: "Hip Abduction", muscle: "glutes", he: "הרחקת ירך במכונה" },
  { name: "Hip Adduction", muscle: "glutes", he: "קירוב ירך במכונה" },
  { name: "Sumo Squat", muscle: "glutes", he: "סקוואט סומו" },
  { name: "Curtsy Lunge", muscle: "glutes", he: "לאנג׳ צולב" },
  { name: "Frog Pump", muscle: "glutes", he: "פרוג פאמפ" },

  // ---------- CALVES ----------
  { name: "Standing Calf Raise", muscle: "calves", he: "הרמת עקבים בעמידה" },
  { name: "Seated Calf Raise", muscle: "calves", he: "הרמת עקבים בישיבה" },
  { name: "Leg Press Calf Raise", muscle: "calves", he: "הרמת עקבים בלחיצת רגליים" },
  { name: "Donkey Calf Raise", muscle: "calves", he: "הרמת עקבים בהטיה" },
  { name: "Single-Leg Calf Raise", muscle: "calves", he: "הרמת עקבים רגל אחת" },

  // ---------- CORE ----------
  { name: "Plank", muscle: "core", he: "פלאנק" },
  { name: "Side Plank", muscle: "core", he: "פלאנק צד" },
  { name: "Crunch", muscle: "core", he: "כפיפות בטן" },
  { name: "Cable Crunch", muscle: "core", he: "כפיפות בטן בפולי" },
  { name: "Sit-Up", muscle: "core", he: "בטן מלאה" },
  { name: "Decline Sit-Up", muscle: "core", he: "בטן בשיפוע שלילי" },
  { name: "Leg Raise", muscle: "core", he: "הרמת רגליים" },
  { name: "Hanging Leg Raise", muscle: "core", he: "הרמת רגליים בתלייה" },
  { name: "Hanging Knee Raise", muscle: "core", he: "הרמת ברכיים בתלייה" },
  { name: "Toes to Bar", muscle: "core", he: "רגליים למוט" },
  { name: "Russian Twist", muscle: "core", he: "טוויסט רוסי" },
  { name: "Bicycle Crunch", muscle: "core", he: "כפיפות אופניים" },
  { name: "V-Up", muscle: "core", he: "וי-אפ" },
  { name: "Hollow Body Hold", muscle: "core", he: "הולו בודי" },
  { name: "Ab Rollout", muscle: "core", he: "גלגלת בטן" },
  { name: "Dead Bug", muscle: "core", he: "דד באג" },
  { name: "Bird Dog", muscle: "core", he: "בירד דוג" },
  { name: "Pallof Press", muscle: "core", he: "פאלוף פרס" },
  { name: "Cable Woodchopper", muscle: "core", he: "חיטוב עצים בפולי" },
  { name: "Mountain Climber", muscle: "core", he: "מטפסי הרים" },
  { name: "Flutter Kicks", muscle: "core", he: "בעיטות רפרוף" },
  { name: "Windshield Wipers", muscle: "core", he: "מגבים" },
  { name: "Dragon Flag", muscle: "core", he: "דגל הדרקון" },
  { name: "L-Sit", muscle: "core", he: "ישיבת L" },
  { name: "Suitcase Carry", muscle: "core", he: "נשיאת מזוודה" },

  // ---------- CARDIO ----------
  { name: "Treadmill Run", muscle: "cardio", he: "ריצה על הליכון" },
  { name: "Incline Walk", muscle: "cardio", he: "הליכה בשיפוע" },
  { name: "Outdoor Run", muscle: "cardio", he: "ריצה בחוץ" },
  { name: "Sprint Intervals", muscle: "cardio", he: "אינטרוולים ספרינט" },
  { name: "Rowing Machine", muscle: "cardio", he: "מכונת חתירה" },
  { name: "Ski Erg", muscle: "cardio", he: "סקי ארג" },
  { name: "Stationary Bike", muscle: "cardio", he: "אופני כושר" },
  { name: "Assault Bike", muscle: "cardio", he: "אופני אוויר" },
  { name: "Elliptical", muscle: "cardio", he: "אליפטיקל" },
  { name: "Stair Climber", muscle: "cardio", he: "מכונת מדרגות" },
  { name: "Jump Rope", muscle: "cardio", he: "קפיצה בחבל" },
  { name: "Jumping Jacks", muscle: "cardio", he: "קפיצות פישוק" },
  { name: "Swimming", muscle: "cardio", he: "שחייה" },
  { name: "Heavy Bag", muscle: "cardio", he: "שק אגרוף" },

  // ---------- FULL BODY / CONDITIONING ----------
  { name: "Burpee", muscle: "fullbody", he: "ברפי" },
  { name: "Box Jump", muscle: "fullbody", he: "קפיצה לקופסה" },
  { name: "Jump Squat", muscle: "fullbody", he: "סקוואט קפיצה" },
  { name: "Battle Ropes", muscle: "fullbody", he: "חבלי קרב" },
  { name: "Sled Push", muscle: "fullbody", he: "דחיפת מזחלת" },
  { name: "Sled Pull", muscle: "fullbody", he: "משיכת מזחלת" },
  { name: "Farmer's Walk", muscle: "fullbody", he: "הליכת פארמר" },
  { name: "Kettlebell Swing", muscle: "fullbody", he: "סווינג קטלבל" },
  { name: "Thruster", muscle: "fullbody", he: "תראסטר" },
  { name: "Power Clean", muscle: "fullbody", he: "פאואר קלין" },
  { name: "Clean and Jerk", muscle: "fullbody", he: "קלין אנד ג'רק" },
  { name: "Snatch", muscle: "fullbody", he: "סנאץ'" },
  { name: "Turkish Get-Up", muscle: "fullbody", he: "טורקיש גט-אפ" },
  { name: "Bear Crawl", muscle: "fullbody", he: "זחילת דוב" },
  { name: "Tire Flip", muscle: "fullbody", he: "הפיכת צמיג" },
  { name: "Wall Ball", muscle: "fullbody", he: "וול בול" },
  { name: "Man Maker", muscle: "fullbody", he: "מן מייקר" },
];

export const HEBREW_ALIASES: Record<string, string> = Object.fromEntries(
  EXERCISE_CATALOG.map(exercise => [exercise.name, exercise.he]),
);

export function muscleLabel(muscle: string): string {
  return MUSCLE_LABELS[muscle] ?? muscle;
}
